# Generated by Django 2.0 on 2019-04-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20190420_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user/default/4.png', upload_to='user/%Y/%m', verbose_name='头像'),
        ),
    ]
