# Generated by Django 2.0 on 2019-04-20 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='academy',
            table=None,
        ),
    ]
