# Generated by Django 2.0 on 2019-05-19 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='机构名称')),
                ('category', models.IntegerField(choices=[(1, '学院'), (2, '工作室'), (3, '小组')], verbose_name='机构类别')),
                ('email', models.EmailField(max_length=30, verbose_name='联系邮箱')),
                ('phone', models.CharField(max_length=15, verbose_name='联系电话')),
                ('intro', models.TextField(verbose_name='机构简介')),
                ('image', models.ImageField(default='Publisher/default.png', max_length=50, upload_to='Publisher/%Y/%m', verbose_name='封面图')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击量')),
                ('course_num', models.IntegerField(default=0, verbose_name='课程数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='入驻时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '机构',
                'verbose_name_plural': '机构',
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='教师名称')),
                ('intro', models.CharField(max_length=100, verbose_name='简介')),
                ('course_num', models.IntegerField(default=0, verbose_name='课程数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击量')),
                ('title', models.IntegerField(choices=[(1, '讲师'), (2, '副教授'), (3, '教授'), (4, '学生')], verbose_name='教师职称')),
                ('contact', models.CharField(default='暂未透露', max_length=30, verbose_name='联系方式')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.Publisher', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
    ]
