# Generated by Django 2.0 on 2019-05-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_teacher_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='point',
            field=models.CharField(default='风趣幽默，专业知识过硬', max_length=30, verbose_name='教学特点'),
        ),
    ]
