# Generated by Django 2.0 on 2019-05-19 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
        ('course', '0002_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='publisher.Publisher', verbose_name='发布方'),
            preserve_default=False,
        ),
    ]
