# Generated by Django 2.0 on 2019-05-19 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='chapter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.Chapter', verbose_name='所属章节'),
            preserve_default=False,
        ),
    ]
