# Generated by Django 2.0 on 2019-05-19 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_teacher_avatar'),
        ('course', '0005_video_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='publisher',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='publisher.Teacher', verbose_name='教师'),
            preserve_default=False,
        ),
    ]
