# Generated by Django 2.0 on 2019-05-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20190519_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='计算机基础', max_length=20, verbose_name='课程类别'),
        ),
    ]
