# Generated by Django 2.0 on 2019-05-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresource',
            name='time',
            field=models.IntegerField(default=0, verbose_name='视频长度(秒)'),
        ),
    ]
