# Generated by Django 2.0 on 2019-05-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_courseresource_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseresource',
            name='time',
        ),
        migrations.AddField(
            model_name='video',
            name='time',
            field=models.IntegerField(default=0, verbose_name='视频长度(秒)'),
        ),
    ]
