# Generated by Django 2.0 on 2019-05-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20190524_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='harvest',
            field=models.CharField(default='入门计算机编程', max_length=50, verbose_name='课程收获'),
        ),
        migrations.AddField(
            model_name='course',
            name='notice',
            field=models.CharField(default='具备计算机基础知识', max_length=50, verbose_name='课程须知'),
        ),
    ]
