# Generated by Django 2.0 on 2019-05-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '课程'), (2, '教师'), (3, '机构')], default=1, verbose_name='收藏类型'),
        ),
    ]
