# Generated by Django 2.0 on 2019-05-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190516_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(max_length=30, verbose_name='验证码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user/default/2.png', upload_to='user/%Y/%m', verbose_name='头像'),
        ),
    ]
