# Generated by Django 2.0 on 2019-05-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190518_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user/default/5.png', upload_to='user/%Y/%m', verbose_name='头像'),
        ),
    ]
