# Generated by Django 2.0 on 2019-05-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190518_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user/default/4.jpg', upload_to='user/%Y/%m', verbose_name='头像'),
        ),
    ]
