# Generated by Django 2.0 on 2019-04-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190413_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='image/default/1.png', upload_to='image/%Y/%m', verbose_name='头像'),
        ),
    ]
