# Generated by Django 2.0 on 2019-04-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190417_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='image/default/2.png', upload_to='image/%Y/%m', verbose_name='头像'),
        ),
    ]
