# Generated by Django 2.0 on 2019-05-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190519_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user/default/default4.jpg', upload_to='user/%Y/%m', verbose_name='头像'),
        ),
    ]
